//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1_BORRAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_22
    {
        public string col1 { get; set; }
        public long pk1 { get; set; }
        public Nullable<long> fk_pk1 { get; set; }
    
        public virtual Table_Borrar Table_Borrar { get; set; }
    }
}
